### ISSUE TITLE
Follow-up to issue #6: Change existing analysis scripts to use the coinsmeg_data module for constructing file paths and loading data

### ISSUE THREAD

**Issue by cedricfoucault** [CCNHuntLab/coins-meg#8]
Follow-up to issue #6: Change existing analysis scripts to use the data module for constructing file paths and loading data.

See PR #7 for the definition of the module (coinsmeg_data.py) and an example use of this module.

**Comment by cedricfoucault** [comment]
Perhaps @amyxli would be well-suited to perform these changes, as the author of the existing scripts (feel free to assign yourself).

I don't think it's necessary to change all the scripts if some of them are not going to be used anymore (for those, we could probably either delete them or document that they are no longer maintained).

**Comment by lhuntneuro** [comment]
May not be addressed on the maxfiltering script, which is why I've reopened it for now.
